sudo: required
services:
    - docker

before_install:
    - docker build -t eloch21/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run eloch21/react-test npm test -- --coverage
    # ensure test script exits with "-- --coverage"

after_success:
    - docker build -t eloch21/multi-client ./client
    - docker build -t eloch21/multi-nginx ./nginx
    - docker build -t eloch21/multi-server ./server
    - docker build -t eloch21/multi-worker ./worker
    # Login to the docker CLI
    # Set the env in travis CI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to dockerhub
    - docker push eloch21/multi-client
    - docker push eloch21/multi-nginx
    - docker push eloch21/multi-server
    - docker push eloch21/multi-worker
    

